# Generated by Django 4.2.8 on 2024-01-03 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agencyId', models.AutoField(primary_key=True, serialize=False)),
                ('agencyName', models.CharField(max_length=100)),
                ('agencyDescription', models.TextField(blank=True, help_text='Tell us about your agency...', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('countryUser', django_countries.fields.CountryField(max_length=2)),
                ('userType', models.CharField(choices=[('tourist', 'Tourist'), ('tourism_agency', 'Tourism Agency')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('packageId', models.AutoField(primary_key=True, serialize=False)),
                ('packageName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Add a aditional description...', null=True)),
                ('duration', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField()),
                ('availableSlots', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True, help_text='Comment us about your experience...', null=True)),
                ('score', models.CharField(choices=[('1.0', '1 star'), ('2.0', '2 stars'), ('3.0', '3 stars'), ('4.0', '4 stars'), ('5.0', '5 stars')], max_length=3, null=True)),
                ('agencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.agency')),
            ],
        ),
    ]
